### ISSUE TITLE
How to add adnl adress to ton domain 

### ISSUE THREAD

**Issue by doe-chain** [tonutils/reverse-proxy#13]
Hi, i have a problem - i have working adnl address now, 
but script falling with error when i try to generate QR code
 is there a way to add this adnl to my ton site without QR code, just from private key that stored in config file  ? 
`main.setupDomain(0xc000188980, {0x7fff88e106ab, 0xa}, {0xc00026e300, 0x20, 0x20})
	/Users/xssnick/dev/ton/reverse-proxy/cmd/proxy/main.go:211 +0x865
main.main()
	/Users/xssnick/dev/ton/reverse-proxy/cmd/proxy/main.go:120 +0x40e`

**Comment by xssnick** [comment]
Hi, you receiving error each time? What is your domain? (If not a secret)

**Comment by doe-chain** [comment]
i have no domain yet, imputing random name - just to get the QR code

**Comment by doe-chain** [comment]
`goroutine 1 [running]:
main.setupDomain(0xc0000ac700, {0x7fffe58926a8, 0xe}, {0xc0004824e0, 0x20, 0x20})
	/Users/xssnick/dev/ton/reverse-proxy/cmd/proxy/main.go:211 +0x865
main.main()
	/Users/xssnick/dev/ton/reverse-proxy/cmd/proxy/main.go:120 +0x40e
`
with foundation.ton

**Comment by xssnick** [comment]
Try to check `external_ip` field in your config file, looks like external ip was not detected and it fails

**Comment by doe-chain** [comment]
thanks, it work now
