### ISSUE TITLE
How to get HEX for DNS "Ton site address" field ?

### ISSUE THREAD

**Issue by websharik** [tonutils/reverse-proxy#24]
I got error ```Error: invalid adnl hex length``` when try insert just .adnl address. So its because HEX required.

![2024-08-01_04-19-07](https://github.com/user-attachments/assets/f7c3d4b2-16dd-4066-b746-6ffa86144c28)

**Comment by websharik** [comment]
Waiting https://github.com/tonutils/reverse-proxy/pull/23

**Comment by xssnick** [comment]
Merged, available in v0.3.3

By the way, you can just scan qr from terminal and execute transaction, so domain will be linked
