### ISSUE TITLE
About proxy pass to external url

### ISSUE THREAD

**Issue by mmqnym** [tonutils/reverse-proxy#26]
My proxy and website are hosted on different servers.
Can I set `proxy_pass` to an external url hosted on any saas platform like Vercel?
I changed the `proxy_pass` in `config.json` to `https://<my_domain>`, and then restarted the proxy. Finally, I used Tonkeeper to view my website (ton://<my_linked_ton_domain>), I got an error page:

`Error loading page`
`Domain: undifined`
`Error Code: -2`
`Description: net::ERR_NAME_NOT_RESOLVED`

These platform not provide static IP address, is this error means I need a static IP address?

**Comment by Nashev** [comment]
Why it is completed? What the answer?
