### ISSUE TITLE
http: proxy error: dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by webportnoy** [tonutils/reverse-proxy#37]
1. Starting reverse-proxy  successfully
2. Opened udp port from config
3. Created site with apache on domain pavelkuznetsov.ton
4. Try to open pavelkuznetsov.ton whith internal telegram browser
5. Server console prints:
```
2024/09/26 11:45:41 request: GET pavelkuznetsov.ton /
2024/09/26 11:45:41 http: proxy error: dial tcp 127.0.0.1:80: connect: connection refused
```
Tried to toggle on/off nginx for this domain - same problem

**Comment by webportnoy** [comment]
Changed server ip address from 127.0.0.1 to real server ip in config.json
It works now.

**Comment by xssnick** [comment]
If domain is already configured you can run without this flag.

The reason of this error are public liteservers not in sync
